### ISSUE TITLE
Ошибка преобразования

### ISSUE THREAD

**Issue by mikeborisov78** [TrueGameover/php-keyboard-input-correction#1]
https://github.com/TrueGameover/php-keyboard-input-correction/blob/63d0abe9140deb00ac1cde6d1156b93495b8cad1/src/correctors/WrongLayoutCorrector.php#L71

Добрый день.
Может проект уже и забросили, но есть небольшая ошибка в коде.
Например, фраза "30 lytq 10 yjxtq" преобразуется во фразу "3 дней 1 ночей". 0 съедается.
Если будет время и возможность, поправьте пожалуйста
0 съедается этой функцией

**Comment by TrueGameover** [comment]
Поправил. Там ошибка в том что "0" преобразовывался в false и не проходил условие.
